### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by hugolpz** [parlr/ruby-font-creator#25]
```
cri-ninja@hp-840:~/yug/Hanzi-Pinyin-Font$ npm start

> hanzi-pinyin-font@ start /home/cri-ninja/yug/Hanzi-Pinyin-Font
> node --max_old_space_size=8192 --optimize_for_size --max_executable_size=4096 --stack_size=4096 --require babel-core/register ./index.js

/home/cri-ninja/yug/Hanzi-Pinyin-Font/index.js:49
    var svgContent = _svg2.default.wrap([_ruby2.default.text(char.glyph, _layouts2.default.bottom.glyph(options)), _ruby2.default.annotation(char.ruby, _layouts2.default.top.ruby(options))]);
                                                                                                                                                                              ^

TypeError: _layouts2.default.top.ruby is not a function
    at generateSvg (/home/cri-ninja/yug/Hanzi-Pinyin-Font/index.js:23:45)
    at /home/cri-ninja/yug/Hanzi-Pinyin-Font/index.js:79:5
    at /home/cri-ninja/yug/Hanzi-Pinyin-Font/node_modules/jsonfile/index.js:46:5
    at /home/cri-ninja/yug/Hanzi-Pinyin-Font/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

npm ERR! Linux 4.4.0-70-generic
npm ERR! argv "/home/cri-ninja/.nvm/versions/node/v6.9.1/bin/node" "/home/cri-ninja/.nvm/versions/node/v6.9.1/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! hanzi-pinyin-font@ start: `node --max_old_space_size=8192 --optimize_for_size --max_executable_size=4096 --stack_size=4096 --require babel-core/register ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hanzi-pinyin-font@ start script 'node --max_old_space_size=8192 --optimize_for_size --max_executable_size=4096 --stack_size=4096 --require babel-core/register ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hanzi-pinyin-font package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --max_old_space_size=8192 --optimize_for_size --max_executable_size=4096 --stack_size=4096 --require babel-core/register ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hanzi-pinyin-font
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hanzi-pinyin-font
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cri-ninja/yug/Hanzi-Pinyin-Font/npm-debug.log
```

![screenshot from 2017-03-30 17-42-45](https://cloud.githubusercontent.com/assets/1420189/24513876/abfae396-1572-11e7-9aeb-91a9e4519d63.png)

[npm-debug..log.txt](https://github.com/parlr/Hanzi-Pinyin-Font/files/883036/npm-debug.log.txt)

----
Note de version : 
```
node -v
v6.9.1
```

**Comment by edouard-lopez** [comment]
@hugolpz I forgot to push some commit, could you try again ?
